drivers/misc: mediatek: m4u: drop unused func
../drivers/misc/mediatek/m4u/2.0/m4u_debug.c:49:12: error: unused function m4u_test_map_kernel [-Werror,-Wunused-function]
   49 | static int m4u_test_map_kernel(void)
      |            ^~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: fukiame <fukiame@proton.me>