drivers/misc: mediatek: eccci: drop unused var
../drivers/misc/mediatek/eccci/hif/ccci_debug_info.c:45:19: error: unused variable s_recv_data_info_lock [-Werror,-Wunused-variable]
   45 | static spinlock_t s_recv_data_info_lock;
      |                   ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: fukiame <fukiame@proton.me>