Revert "lib/string.c: Optimize memchr()"
../lib/string.c:1134:3: error: implicit declaration of function
'MEMCHR_MASK_GEN' [-Werror,-Wimplicit-function-declaration]
 1134 |                 MEMCHR_MASK_GEN(mask);
       |                 ^
       1 error generated.

This reverts commit ece393261912ebf2510312c14f7a5f772dfc75eb.

Signed-off-by: fukiame <fukiame@proton.me>